name: Node.js CI

on:
  pull_request:
    branches: 
      - main
      - develop

jobs:
  build: 
    runs-on: ubuntu-latest
    defaults:
      run:
          working-directory: ./web-intf/backend/
          
    timeout-minutes: 3

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './web-intf/backend/package-lock.json'

    - name: Install Dependencies
      run: npm ci
    
    - name: Add environment variables
      run: |
        touch .env
        echo MONGODB_URI="mongodb+srv://kendrick807:27190670kendrick@votedata.uz4trxo.mongodb.net/?retryWrites=true&w=majority
        JWT_SECRET=m6<48g^C0bF=gVM/d[ghW:7]`1HLzjjViAsJ*N'j!Hwwej]8V;,P2l3K_P1{D," >> .env

    - name: Build Project
      run: npm run build --if-present 
  test:
    needs: [build]

    runs-on: ubuntu-latest
    defaults:
      run:
          working-directory: ./web-intf/backend/test

    timeout-minutes: 5

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './web-intf/backend/package-lock.json'

    - name: Install Dependencies
      run: npm ci

    - name: Run Mocha Unit Tests
      run: npm run test