name: Node.js CI

on:
  pull_request:
    branches: 
      - main
      - develop

jobs:
  set_env_vars: 
    runs-on: ubuntu-latest
          
    timeout-minutes: 1

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - name: Add environment variables
      run: |
        touch .env
        echo MONGODB_URI=${{ secrets.MONGODB_URI }} >> .env
        echo PORT=${{ secrets.PORT }} >> .env
        echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> .env

  build: 
    needs: [set_env_vars]
    runs-on: ubuntu-latest
    defaults:
      run:
          working-directory: ./web-intf/backend/
          
    timeout-minutes: 5

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './web-intf/backend/package-lock.json'

    - name: Install Dependencies
      run: npm ci
    
    - name: Add environment variables
      run: |
        touch .env
        echo MONGODB_URI=${{ secrets.MONGODB_URI }} >> .env
        echo PORT=${{ secrets.PORT }} >> .env
        echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> .env

    - name: Build Project
      run: npm run build --if-present 
  test:
    needs: [build]

    runs-on: ubuntu-latest
    defaults:
      run:
          working-directory: ./web-intf/backend/test

    timeout-minutes: 5

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './web-intf/backend/package-lock.json'

    - name: Install Dependencies
      run: npm ci

    - name: Run Mocha Unit Tests
      run: npm run test